/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jeannie
 */
public class frmInstructions extends javax.swing.JFrame {

    /**
     * Creates new form frmInstructions
     */
    public frmInstructions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        lblInstr1 = new javax.swing.JLabel();
        lblInstr2 = new javax.swing.JLabel();
        lblInstr3 = new javax.swing.JLabel();
        lblInstr4 = new javax.swing.JLabel();
        lblInstr5 = new javax.swing.JLabel();
        lblInstr6 = new javax.swing.JLabel();
        lblInstr7 = new javax.swing.JLabel();
        lblInstr8 = new javax.swing.JLabel();
        lblInstr9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setFont(new java.awt.Font("Courier Prime", 0, 48)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 125)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("GAME RULES");

        lblInstr1.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        lblInstr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr1.setText("Rock paper scissors lizard spock is similar to");

        lblInstr2.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        lblInstr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr2.setText("rock paper scissors, but with the two new additions");

        lblInstr3.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        lblInstr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr3.setText("of lizard and spock. The rules are as follows:");

        lblInstr4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblInstr4.setForeground(new java.awt.Color(0, 102, 102));
        lblInstr4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr4.setText("LIZARD: poisons SPOCK and eats PAPER");

        lblInstr5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblInstr5.setForeground(new java.awt.Color(0, 102, 102));
        lblInstr5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr5.setText("ROCK: crushes SCISSORS and crushes LIZARD");

        lblInstr6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblInstr6.setForeground(new java.awt.Color(0, 102, 102));
        lblInstr6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr6.setText("PAPER: covers ROCK and disproves SPOCK");

        lblInstr7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblInstr7.setForeground(new java.awt.Color(0, 102, 102));
        lblInstr7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr7.setText("SCISSORS: cuts PAPER and decapitates LIZARD");

        lblInstr8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblInstr8.setForeground(new java.awt.Color(0, 102, 102));
        lblInstr8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr8.setText("SPOCK: smashes SCISSORS and vaporizes ROCK");

        lblInstr9.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        lblInstr9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr9.setText("Take fewer turns to achieve a higher score!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblInstr8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInstr7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblInstr5, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblInstr6, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(9, 9, 9))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblInstr4, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)))
                    .addComponent(lblInstr3, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstr2, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstr1, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(723, 723, 723))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1915, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInstr9, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblInstr1)
                .addGap(18, 18, 18)
                .addComponent(lblInstr2)
                .addGap(18, 18, 18)
                .addComponent(lblInstr3)
                .addGap(56, 56, 56)
                .addComponent(lblInstr5)
                .addGap(32, 32, 32)
                .addComponent(lblInstr6)
                .addGap(36, 36, 36)
                .addComponent(lblInstr7)
                .addGap(38, 38, 38)
                .addComponent(lblInstr4)
                .addGap(39, 39, 39)
                .addComponent(lblInstr8)
                .addGap(55, 55, 55)
                .addComponent(lblInstr9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //sets frmStart to be visible and current form invisible
        this.setVisible(false);
        new frmStart().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInstructions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInstr1;
    private javax.swing.JLabel lblInstr2;
    private javax.swing.JLabel lblInstr3;
    private javax.swing.JLabel lblInstr4;
    private javax.swing.JLabel lblInstr5;
    private javax.swing.JLabel lblInstr6;
    private javax.swing.JLabel lblInstr7;
    private javax.swing.JLabel lblInstr8;
    private javax.swing.JLabel lblInstr9;
    // End of variables declaration//GEN-END:variables
}
