/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.*;
import java.util.*;

/**
 *
 * @author Jeannie
 */
public class frmLeaderBoards extends javax.swing.JFrame {
    
    public static int[] findTop3(ArrayList<String> a){
        //declares variables
        int first=0, second=0, third=0;//variables to store indices
        int temp, compTemp = 1000;//temporary variables used for comparison
        
        for (int i = 1; i<a.size(); i=i+2){//traverses the array list for scores
            temp = Integer.parseInt(a.get(i));
            if (temp<compTemp){
                first = i;//set index of first high score
                compTemp = temp;
            }
        }
        
        compTemp = 1000;//resets temporary variable
        for (int i = 1; i<a.size(); i=i+2){//traverses the array list for scores
            temp = Integer.parseInt(a.get(i));
            if (temp<compTemp&i!=first){
                second = i;//set index of second high score
                compTemp = temp;
            }
        }
        
        compTemp = 1000;//resets temporary variable
        for (int i = 1; i<a.size(); i=i+2){//traverses the array list for scores
            temp = Integer.parseInt(a.get(i));
            if (temp<compTemp&i!=first&i!=second){
                third = i;//set index of third high score
                compTemp = temp;
            }
        }
        
        
        int[] indices = {first, second, third};
        return indices;//returns an integer array of indices
    }
    
    /**
     * Creates new form frmStart
     */
    public frmLeaderBoards() {
        initComponents();
        int[] top = new int[3];
        
        ArrayList <String> scores = new ArrayList <String>(); //creates an ArrayList of scores
        BufferedReader br = null;
        
        try{ //buffered reader adds books to the ArrayList
            br = new BufferedReader(new FileReader("scores.txt"));
            String score;
            while ((score = br.readLine()) != null ){
                scores.add(score);
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        
        String [] highscores = new String[scores.size()];//creates a String array from the bookList array list
        scores.toArray(highscores);
        
        top = findTop3(scores);//calls the findTop3 method
        
        //sets labels to displays the name and corresponding 
        lblScore1.setText(highscores[top[0]]);
        lblName1.setText(highscores[top[0]-1]);
        lblScore2.setText(highscores[top[1]]);
        lblName2.setText(highscores[top[1]-1]);
        lblScore3.setText(highscores[top[2]]);
        lblName3.setText(highscores[top[2]-1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();
        lblHeader2 = new javax.swing.JLabel();
        lblHeader3 = new javax.swing.JLabel();
        lblHeader4 = new javax.swing.JLabel();
        lblHeader5 = new javax.swing.JLabel();
        lblHeader6 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblScore1 = new javax.swing.JLabel();
        lblScore2 = new javax.swing.JLabel();
        lblScore3 = new javax.swing.JLabel();
        lblInstr1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnFindScore = new javax.swing.JButton();
        lblInstr2 = new javax.swing.JLabel();
        lblFoundScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Courier Prime", 0, 48)); // NOI18N
        jButton2.setText("Back to Game");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 150)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("LEADERBOARD");

        lblHeader1.setFont(new java.awt.Font("Courier Prime", 0, 125)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader1.setText("1");

        lblHeader2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 125)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader2.setText("Name");

        lblHeader3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 125)); // NOI18N
        lblHeader3.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader3.setText("Score");

        lblHeader4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 125)); // NOI18N
        lblHeader4.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader4.setText("Rank");

        lblHeader5.setFont(new java.awt.Font("Courier Prime", 0, 125)); // NOI18N
        lblHeader5.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader5.setText("2");

        lblHeader6.setFont(new java.awt.Font("Courier Prime", 0, 125)); // NOI18N
        lblHeader6.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader6.setText("3");

        lblName1.setFont(new java.awt.Font("Courier Prime", 0, 125)); // NOI18N
        lblName1.setForeground(new java.awt.Color(0, 102, 102));
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblName2.setFont(new java.awt.Font("Courier Prime", 0, 125)); // NOI18N
        lblName2.setForeground(new java.awt.Color(0, 102, 102));
        lblName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblName3.setFont(new java.awt.Font("Courier Prime", 0, 125)); // NOI18N
        lblName3.setForeground(new java.awt.Color(0, 102, 102));
        lblName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblScore1.setFont(new java.awt.Font("Courier Prime", 0, 125)); // NOI18N
        lblScore1.setForeground(new java.awt.Color(0, 102, 102));
        lblScore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblScore2.setFont(new java.awt.Font("Courier Prime", 0, 125)); // NOI18N
        lblScore2.setForeground(new java.awt.Color(0, 102, 102));
        lblScore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblScore3.setFont(new java.awt.Font("Courier Prime", 0, 125)); // NOI18N
        lblScore3.setForeground(new java.awt.Color(0, 102, 102));
        lblScore3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblInstr1.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        lblInstr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr1.setText("Enter a name to find the associated score:");

        txtName.setFont(new java.awt.Font("Courier Prime", 0, 48)); // NOI18N

        btnFindScore.setFont(new java.awt.Font("Courier Prime", 0, 36)); // NOI18N
        btnFindScore.setText("Find Score");
        btnFindScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindScoreActionPerformed(evt);
            }
        });

        lblInstr2.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        lblInstr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstr2.setText("Player Score:");

        lblFoundScore.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        lblFoundScore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFoundScore.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(734, 734, 734))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1915, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296)
                        .addComponent(lblHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHeader5, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHeader6, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblScore3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInstr1)
                                .addGap(45, 45, 45)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFindScore, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(289, 289, 289)
                                .addComponent(lblInstr2)
                                .addGap(26, 26, 26)
                                .addComponent(lblFoundScore, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(lblHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1525, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHeader5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblScore2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblScore3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstr1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoundScore, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFindScore, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInstr2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(295, 295, 295)
                    .addComponent(lblHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1063, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new frmLizardSpock().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnFindScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindScoreActionPerformed
        
        ArrayList <String> scores = new ArrayList <String>(); //creates an ArrayList of scores
        BufferedReader br = null;
        
        try{ //buffered reader adds books to the ArrayList
            br = new BufferedReader(new FileReader("scores.txt"));
            String score;
            while ((score = br.readLine()) != null ){
                scores.add(score);
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        
        String [] highscores = new String[scores.size()];//creates a String array from the bookList array list
        scores.toArray(highscores);        
        
        //declare variable to store index of found name
        int foundIndex = -1;
        //declare variable to store user input
        String name = txtName.getText();
        
        //searches for index of the value of name
        for (int i = 0; i<highscores.length; i++){
            if (highscores[i].equals(name)){
                foundIndex=i;
            }
        }
        
        if (foundIndex==-1){//if name is not fount
            lblFoundScore.setText("Not Found");
        }
        else{//when name is found
            lblFoundScore.setText(highscores[foundIndex+1]);//displays score for user
        }
        
    }//GEN-LAST:event_btnFindScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindScore;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblFoundScore;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JLabel lblHeader3;
    private javax.swing.JLabel lblHeader4;
    private javax.swing.JLabel lblHeader5;
    private javax.swing.JLabel lblHeader6;
    private javax.swing.JLabel lblInstr1;
    private javax.swing.JLabel lblInstr2;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblScore1;
    private javax.swing.JLabel lblScore2;
    private javax.swing.JLabel lblScore3;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
